tasktrack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from track import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^accounts/registration/', core_views.signup, name="signup"),
    url(r'', include('track.urls')),
]

track/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='start.html'), name='start'),
    url(r'^today/$', views.today, name='today_list'),

    url(r'^tasks/$', views.tasks_filter, name='tasks_filter'),
    url(r'^tasks/new/$', views.task_new, name='task_new'),
    url(r'^tasks/(?P<pk>\d+)/$', views.task_detail, name='task_detail'),
    url(r'^tasks/(?P<pk>\d+)/edit/$', views.task_edit, name='task_edit'),
    url(r'^tasks/(?P<pk>\d+)/done/$', views.task_done, name='task_done'),
    url(r'^tasks/(?P<pk>\d+)/delete/$', login_required(views.DeleteTaskView.as_view()), name='task_delete'),
    url(r'^tasks/(?P<pk>\d+)/new_subtask', views.subtask_new, name='subtask_new'),
    url(r'^tasks/groups/$', views.tasks_groups, name='tasks_groups'),
    url(r'^tasks/groups/(?P<pk>\d+)/$', views.tasks_group, name='tasks_group'),

    url(r'^events/$', views.events_filter, name='events_filter'),
    url(r'^events/new/$', views.event_new, name='event_new'),
    url(r'^events/(?P<pk>\d+)/$', views.event_detail, name='event_detail'),
    url(r'^events/(?P<pk>\d+)/edit/$', views.event_edit, name='event_edit'),
    url(r'^events/(?P<pk>\d+)/delete/$', login_required(views.DeleteEventView.as_view()), name='event_delete'),
    url(r'^events/groups/$', views.events_groups, name='events_groups'),
    url(r'^events/groups/(?P<pk>\d+)/$', views.events_group, name='events_group'),
    url(r'^events/plans$', views.plans_filter, name='plans_filter'),
    url(r'^events/plans/new_plan$', views.event_plan_new, name='event_plan_new'),
    url(r'^events/plans/new_plan_days/$', views.event_plan_days_new, name='event_plan_days_new'),
    url(r'^events/plans/(?P<event_pk>\d+)/edit/$', views.event_plan_edit, name='event_plan_edit'),

    url(r'^groups/$', views.group_new, name='group_new'),
]

track/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from multiselectfield import MultiSelectField
from dateutil.relativedelta import relativedelta


class Group(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Task(models.Model):
    """Implements Task table."""
    title = models.CharField(max_length=50)
    create_datetime = models.DateTimeField(default=timezone.now)
    deadline_date = models.DateField(null=True, blank=True)
    priority = models.IntegerField(default=0, choices=(
        (0, "No"),
        (1, "Low"),
        (2, "Medium"),
        (3, "High")
    ))
    group = models.ManyToManyField(Group, blank=True, default=None)
    description = models.TextField(blank=True)
    access = models.CharField(max_length=1, default="p", choices=(
        ("p", "Private"),
        ("r", "Read"),
        ("w", "Write")
    ))
    is_ready = models.BooleanField(default=False)
    status = models.CharField(max_length=1, default="a", choices=(
        ("a", "Active"),
        ("r", "Ready"),
        ("f", "Failed"),
    ))
    related_tasks = models.TextField(blank=True)
    parent_task = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    edit_datetime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_subtasks(self):
        return Task.objects.filter(parent_task__id=self.id)

    def get_status_style_color(self):
        colors = {"a": "black", "r": "green", "f": "red"}
        return colors[self.status]

    def done(self):
        self._recursive_done_down()
        self._recursive_done_up()

    def _mark_ready(self):
        self.status = "r"
        self.edit_datetime = timezone.now()
        self.save()

    def _recursive_done_down(self):
        self._mark_ready()
        subs = Task.objects.filter(parent_task__id=self.id)
        for sub in subs:
            sub._recursive_done_down()

    def _recursive_done_up(self):
        if self.parent_task:
            parent = self.parent_task
            if (Task.objects.filter(parent_task__id=parent.id, status="r").count() ==
                Task.objects.filter(parent_task__id=parent.id).count()):
                parent._mark_ready()
                parent._recursive_done_up()

    def _mark_failed(self):
        self.status = "f"
        self.edit_datetime = timezone.now()
        self.save()

    def update_status(user):
        failed_titles = []
        failed_tasks = Task.objects.filter(user__id=user.id, status="a", deadline_date__lt=timezone.now().date(),
                                           parent_task__isnull=True)

        parents = []
        for task in failed_tasks:
            failed_titles.append(task.title)
            task._mark_failed()
            if task.parent_task:
                parents.append(task.parent_task)
            failed_titles.extend(task._update_subs_status(user))
        failed_titles.extend(Task._update_parent_tasks_status(parents))
        return failed_titles

    def _update_subs_status(self, user):
        subs = Task.objects.filter(user__id=user.id, status="a", parent_task__id=self.id)
        failed_titles = []
        for sub in subs:
            failed_titles.append(sub.title)
            sub._mark_failed()
            failed_titles.extend(sub._update_subs_status(user))
        return failed_titles

    @staticmethod
    def _update_parent_tasks_status(parents):
        failed_titles = []
        new_parents = []
        for parent in parents:
            if parent.status == "f":
                continue
            if (Task.objects.filter(parent_task__id=parent.id, status="f").count() ==
                    Task.objects.filter(parent_task__id=parent.id).count()):
                failed_titles.append(parent.title)
                parent._mark_failed()
                if parent.parent_task:
                    new_parents.append(parent.parent_task)
        if new_parents:
            failed_titles.extend(Task._update_parent_tasks_status(new_parents))
        return failed_titles


class EventPlan(models.Model):
    """Implements EventPlan table."""
    years = models.PositiveSmallIntegerField(null=True, blank=True, default=0)
    months = models.PositiveSmallIntegerField(null=True, blank=True, default=0)
    days = models.PositiveSmallIntegerField(null=True, blank=True, default=1)
    first_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    edit_datetime = models.DateTimeField(default=timezone.now)

    def is_today(self, date):
        delta_date = relativedelta(days=self.days, months=self.months, years=self.years)
        if date < self.first_date:
            return False
        temp_date = self.first_date
        while temp_date < date:
            temp_date += delta_date
        if temp_date == date:
            return True
        return False


class EventPlanDays(models.Model):
    """Implements EventPlanDays table."""
    days = MultiSelectField(choices=(
        (0, "Monday"),
        (1, "Tuesday"),
        (2, "Wednesday"),
        (3, "Thursday"),
        (4, "Friday"),
        (5, "Saturday"),
        (6, "Sunday")
    ))
    first_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    edit_datetime = models.DateTimeField(default=timezone.now)

    def is_today(self, date):
        DAYS = {
            "Monday": 0,
            "Tuesday": 1,
            "Wednesday": 2,
            "Thursday": 3,
            "Friday": 4,
            "Saturday": 5,
            "Sunday": 6
        }
        if date < self.first_date:
            return False
        repeat_days = [DAYS[d] for d in self.get_days_list()]
        if date.weekday() in repeat_days:
            return True
        return False


class Event(models.Model):
    """Implements Event table."""
    title = models.CharField(max_length=50)
    create_datetime = models.DateTimeField(default=timezone.now)
    date = models.DateField()
    time = models.TimeField()
    priority = models.IntegerField(default=0, choices=(
        (0, "No"),
        (1, "Low"),
        (2, "Medium"),
        (3, "High")
    ))
    group = models.ManyToManyField(Group, blank=True, default=None)
    description = models.TextField(blank=True)
    access = models.CharField(max_length=1, default="p", choices=(
        ("p", "Private"),
        ("r", "Read"),
        ("w", "Write")
    ))
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    edit_datetime = models.DateTimeField(default=timezone.now)
    is_planned = models.BooleanField(default=False)
    plan = models.ForeignKey(EventPlan, on_delete=models.CASCADE, null=True, blank=True)
    plan_days = models.ForeignKey(EventPlanDays, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_plan_first_date(self):
        if not self.is_planned:
            return

        if self.plan:
            return self.plan.first_date
        else:
            return self.plan_days.first_date

    def get_plan_period(self):
        if not self.is_planned:
            return

        if self.plan:
            period = []
            if self.plan.days:
                period.append("{} day(s)".format(self.plan.days))
            if self.plan.months:
                period.append("{} month(s)".format(self.plan.months))
            if self.plan.years:
                period.append("{} year(s)".format(self.plan.years))
            return ",".join(period)
        else:
            return self.plan_days.get_days_display()

track/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Task, Event, EventPlan, EventPlanDays, Group


class AddTaskForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(AddTaskForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = Task
        fields = ('title', 'deadline_date', 'priority', 'group', 'description', )
        widgets = {
            'title': forms.widgets.TextInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'deadline_date': forms.widgets.DateInput(
                attrs={'type': 'date', 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'priority': forms.widgets.Select(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'group': forms.widgets.CheckboxSelectMultiple(attrs={'style': 'margin-bottom: 15px'}),
            'description': forms.Textarea(
                attrs={'cols': 30, 'rows': 3, 'class': 'form-control', 'style': 'margin-bottom: 15px'})
        }


class EditTaskForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(EditTaskForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = Task
        fields = ('title', 'deadline_date', 'priority', 'description',
                  'related_tasks', 'group', 'access',)
        widgets = {
            'title': forms.widgets.TextInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'deadline_date': forms.widgets.DateInput(
                attrs={'type': 'date', 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'priority': forms.widgets.Select(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'access': forms.widgets.Select(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'group': forms.widgets.CheckboxSelectMultiple(attrs={'style': 'margin-bottom: 15px'}),
            'description': forms.Textarea(
                attrs={'cols': 30, 'rows': 3, 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'related_tasks': forms.Textarea(
                attrs={'cols': 30, 'rows': 3, 'class': 'form-control', 'style': 'margin-bottom: 15px'})
        }


class DoneTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = tuple()


class AddEventForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(AddEventForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = Event
        fields = ('title', 'date', 'time', 'priority', 'group', 'description', )
        widgets = {
            'title': forms.widgets.TextInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'date': forms.widgets.DateInput(
                attrs={'type': 'date', 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'time': forms.widgets.TimeInput(
                attrs={'type': 'time', 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'priority': forms.widgets.Select(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'group': forms.widgets.CheckboxSelectMultiple(attrs={'style': 'margin-bottom: 15px'}),
            'description': forms.Textarea(
                attrs={'cols': 30, 'rows': 3, 'class': 'form-control', 'style': 'margin-bottom: 15px'})
        }


class EditEventForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(EditEventForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = Event
        fields = ('title', 'date', 'time', 'priority', 'description', 'group', 'access',)
        widgets = {
            'title': forms.widgets.TextInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'date': forms.widgets.DateInput(
                attrs={'type': 'date', 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'time': forms.widgets.TimeInput(
                attrs={'type': 'time', 'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'priority': forms.widgets.Select(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'access': forms.widgets.Select(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'group': forms.widgets.CheckboxSelectMultiple(attrs={'style': 'margin-bottom: 15px'}),
            'description': forms.Textarea(
                attrs={'cols': 30, 'rows': 3, 'class': 'form-control', 'style': 'margin-bottom: 15px'})
        }


class AddEventPlanForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        days = cleaned_data.get("days")
        months = cleaned_data.get("months")
        years = cleaned_data.get("years")
        if days == 0 and months == 0 and years == 0:
            raise ValidationError("At least one of the fields must be different from 0.")

    class Meta:
        model = EventPlan
        fields = ('days', 'months', 'years')
        widgets = {
            'days': forms.widgets.NumberInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'months': forms.widgets.NumberInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'years': forms.widgets.NumberInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
        }


class AddEventPlanDaysForm(forms.ModelForm):
    class Meta:
        model = EventPlanDays
        fields = ('days',)
        widgets = {'days': forms.widgets.CheckboxSelectMultiple(attrs={'style': 'margin-bottom: 15px'})}


class EditEventPlanForm(forms.ModelForm):

    class Meta:
        model = EventPlan
        fields = ('days', 'months', 'years')
        widgets = {
            'days': forms.widgets.NumberInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'months': forms.widgets.NumberInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
            'years': forms.widgets.NumberInput(attrs={'class': 'form-control', 'style': 'margin-bottom: 15px'}),
        }


class EditEventPlanDaysForm(forms.ModelForm):

    class Meta:
        model = EventPlanDays
        fields = ('days', )
        widgets = {
            'days': forms.widgets.CheckboxSelectMultiple(attrs={'style': 'margin-bottom: 15px'}),
        }


class AddGroupForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(AddGroupForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        if Group.objects.filter(user=self.user, name=name).exists():
            raise ValidationError("Group with that name already exists.")

    class Meta:
        model = Group
        fields = ('name',)
        widgets = {
            'name': forms.TextInput()
        }


class DateForm(forms.Form):
    date = forms.DateField(required=False)

track/templates/track/event_new.html
{% extends 'track/base.html' %}


{% block content %}
    <h1>New event</h1>
    <form method="POST" class="post-form" style="margin-right: 500px">{% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            <div class="">
                <a href="{% url 'today_list' %}">
                    <button type="button" class="btn btn-secondary">Back</button>
                </a>
                <button type="submit" class="save btn btn-primary">Save</button>
            </div>
        </div>
    </form>
{% endblock %}

track/templates/track/events_filter.html
{% extends 'track/base.html' %}


{% block content %}
    <h3>Events</h3>

     <br/>
     <form action="" method="get">
         <div >
             {{date_form.as_p}}
             {{ filter.form.as_p }}
             <button type="submit" class="btn btn-success" ><span class="fa fa-search"></span> Find events!</button>
             <a href="{% url 'event_new' %}" type="button" class="btn btn-primary">
                 <span class="fa fa-plus"></span> Add new event</a>
         </div>
     </form>

     <hr/>

     {% if not filter.qs %}
         <p>Nothing found.</p>
     {% endif %}

     {% for event in filter.qs %}
         {% include 'event_short.html' with event=event with_date=True %}
         <hr/>
     {% endfor %}

{% endblock %}

track/templates/track/group_events_filter.html
{% extends 'track/base.html' %}


{% block content %}

    <h3>Events</h3>
    <br/>
    <form action="" method="GET">
        {{date_form.as_p}}
        <button type="submit" class="btn btn-success"><span class="fa fa-search"></span> Find events!</button>
    </form>

    <hr/>

    {% if not events and not planned_events %}
        <p>Nothing found.</p>
    {% endif %}

    {% for event in events %}
        {% include 'event_short.html' with event=event with_date=True%}
    {% endfor %}

{% endblock %}

track/templates/track/plan_event_short.html
<div class="event">
    <h4><a href="{% url 'event_detail' pk=event.pk %}">{{ event.title }}</a></h4>
    <time>{{ event.time }}</time>
    <p>Start date: {{event.get_plan_first_date}}. Period: {{event.get_plan_period}}</p>
</div>
<hr/>

track/templates/track/plans_filter.html
{% extends 'track/base.html' %}


{% block content %}

    <h3>Event plans</h3>
    <br/>
    <form action="" method="get">
        <div >
            {{ filter.form.as_p }}
            <button type="submit" class="btn btn-success"><span class="fa fa-search"></span> Find plans!</button>
            <a href="{% url 'event_plan_new' %}" type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span> Add new event plan</a>
            <a href="{% url 'event_plan_days_new' %}" type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span> Add new event plan days</a>
        </div>
    </form>

    <hr/>

    {% if not filter.qs %}
        <p>Nothing found.</p>
    {% endif %}

    {% for event in filter.qs %}
        {% include 'plan_event_short.html' with event=event %}
        <hr/>
    {% endfor %}

{% endblock %}

track/templates/track/start.html
{% extends 'track/base.html' %}

{% block content %}
<h1>Welcome to Track application!</h1>


{% endblock %}

track/templates/track/task_delete.html
{% extends 'track/base.html' %}


{% block content %}
    <h1>Delete task?</h1>
    <p>Are you sure you want to delete '{{object.title}}'?</p>
    <form method="POST" action="" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <div class="">
            <a href="{% url 'task_detail' pk=object.pk %}">
                <button type="button" class="btn btn-secondary">Cancel</button>
            </a>
            <button type="submit" class="btn btn-primary"><span class="fa fa-remove"></span> Delete</button>
        </div>
    </form>
{% endblock %}

track/templates/track/task_done.html
{% extends 'track/base.html' %}


{% block content %}

    {% if failed_tasks %}
        {% include 'tasks_failed.html' with failed_tasks=failed_tasks %}
    {% endif %}

    <h1>Task is done?</h1>
    <p>Mark task as ready?</p>
    <form method="POST" action="" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <div class="">
            <a href="{% url 'today_list' %}">
                <button type="button" class="btn btn-secondary">Cansel</button>
            </a>
            <button type="submit" class="btn btn-primary"><span class="fa fa-check"></span> Done!</button>
        </div>
    </form>
{% endblock %}

track/templates/track/task_edit.html
{% extends 'track/base.html' %}


{% block content %}

    {% if failed_tasks %}
        {% include 'tasks_failed.html' with failed_tasks=failed_tasks %}
    {% endif %}

    <form method="POST" class="post-form"  style="margin-right: 500px">{% csrf_token %}
        <h1>Edit task</h1>
        <div class="form-group">
            {{ form.as_p }}

            {% if task.status == "a" and user == task.user %}
            <a href="{% url 'subtask_new' pk=task.pk%}">
                <button type="button" class="btn btn-default" style="margin-bottom: 20px">
                    <span class="glyphicon glyphicon-plus"></span> Add subtask
                </button>
            </a>
            {% endif %}

            <div class="">
                <a href="{% url 'task_detail' pk=task_pk %}">
                    <button type="button" class="btn btn-secondary">Cancel</button>
                </a>
                <button type="submit" class="save btn btn-primary">Save</button>
            </div>
        </div>
    </form>
{% endblock %}

track/templates/track/task_group_selection.html
{% extends 'track/base.html' %}

{% block content %}

    {% if failed_tasks %}
        {% include 'tasks_failed.html' with failed_tasks=failed_tasks %}
    {% endif %}

    {% if not groups %}
        <h2>All groups are empty! Click <a href="{% url 'group_new' %}">here</a> to create new.</h2>
    {% else %}
        <h2>Your groups:</h2>
    {% endif %}

     <br/>
    {% for group in groups %}
        <a href="{% url 'tasks_group' pk=group.pk %}" type="button" class="btn btn-primary btn-lg">{{group.name}}</a>
    {% endfor %}
{% endblock %}

track/templates/track/task_short.html
<div class="task">
    <div class="form-check mb-2 mr-sm-2">
        <h4><a href="{% url 'task_detail' pk=task.pk %}" >{{ task.title }}</a></h4>
        <p>{{ task.description|linebreaksbr }}</p>
        {% if task.status == "a" and request.user == task.user %}
            <a href="{% url 'task_done' pk=task.pk %}" >
                <button class="btn btn-success">
                    <span class="fa fa-check">Do it!</span>
                </button>
            </a>
        {% else %}
            <p style="color: {{task.get_status_style_color}};">Status: {{task.get_status_display}}</p>
        {% endif %}
    </div>
</div>
<hr/>

track/templates/track/tasks_failed.html
<div class="alert alert-danger" role="alert">
  Tasks {{failed_tasks}} are failed!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<hr/>

track/templates/track/tasks_filter.html
{% extends 'track/base.html' %}
{% load widget_tweaks %}

{% block content %}

    {% if failed_tasks %}
        {% include 'tasks_failed.html' with failed_tasks=failed_tasks %}
    {% endif %}

    <h3>Tasks</h3>
    <br/>

    <form action="" method="get">
        {{ filter.form.as_p }}
        <button type="submit" class="btn btn-success"><span class="fa fa-search"></span> Find tasks!</button>
        <a href="{% url 'task_new' %}" type="button" class="btn btn-primary">
            <span class="fa fa-plus"></span> Add new task</a>
    </form>

    <hr/>

    {% if not filter.qs %}
        <p>Nothing found.</p>
    {% endif %}

    {% for task in filter.qs %}
        {% include 'task_short.html' with task=task %}
        <hr/>
    {% endfor %}
{% endblock %}

track/templates/track/today.html
{% extends 'track/base.html' %}

{% block content %}

    {% if failed_tasks %}
        {% include 'tasks_failed.html' with failed_tasks=failed_tasks %}
    {% endif %}

    <!--Tasks with deadline-->
    <form class="form-inline">
        {% if not tasks %}
            <h2>No tasks for today!</h2>

        {% else %}
            <h2>Tasks for today</h2>
        {% endif %}

        <a href="{% url 'task_new' %}" style="margin-left: 20px;">
                <span class="fa fa-plus"></span> Add new
        </a>
    </form>

    {% for task in tasks %}
        {% include 'task_short.html' with task=task %}
    {% endfor %}


    <!--Events-->

    <hr/>
    <form class="form-inline">
        {% if not events %}
            <h2 style="margin-right: 20px;">No events for today!</h2>

        {% else %}
            <h2>Events for today</h2>
        {% endif %}

        <a href="{% url 'event_new' %}" style="margin-left: 20px;">
            <span class="fa fa-plus"></span> Add new
        </a>
    </form>

    {% for event in events %}
        {% include 'event_short.html' with event=event %}
    {% endfor %}

    <!--Plans-->

    <hr/>
    {% if plans %}
        <h2>Plans for today</h2>
    {% endif %}

    {% for event in plans %}
        {% include 'plan_event_short.html' with event=event %}
    {% endfor %}

    <!--Tasks without deadline-->

    <hr/>
    {% if tasks_without_deadline %}
        <h2>Tasks without deadline</h2>

        {% for task in tasks_without_deadline %}
            {% include 'task_short.html' with task=task %}
        {% endfor %}
    {% endif %}
{% endblock %}